language: php
sudo: enabled

php:
    - 7.1
    - 7.2

cache:
    directories:
        - vendor

before_install:
    - phpenv config-rm xdebug.ini || true
    - composer selfupdate

install:
    - composer install --prefer-dist

script:
    - composer check